'use client'

import HeaderNav from "@/components/Header/HeaderNav";
import "./globals.css";
import localFont from "next/font/local";
import { useRef,useState, useEffect } from "react";

const centuryGothic = localFont({
  src: "../../public/assets/fonts/CenturyGothic.ttf",
  variable: "--font-gothic",
});
const bigilla = localFont({
  src: "../../public/assets/fonts/Bigilla.otf",
  variable: "--font-bigilla",
});

// export const metadata = {
//   title: "Gulz",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const headerRef = useRef();
  const [isScrolled, setIsScrolled] = useState(false);

  const handleScroll = () => {
    setIsScrolled(window.scrollY > 100);
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <html lang="en">
      <body
        className={`${centuryGothic.variable} ${bigilla.variable} antialiased`}
      >
        <HeaderNav headerRef={headerRef}
          isScrolled={isScrolled}/>
        {children}
      </body>
    </html>
  );
}