import "./globals.css";
import localFont from "next/font/local";

const centuryGothic = localFont({
  src: "../../public/assets/fonts/CenturyGothic.ttf",
  variable: "--font-gothic",
});

export const metadata = {
  title: "Gulz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${centuryGothic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}