'use client'

import HeaderNav from "@/components/Header/HeaderNav";
import Footer from "@/components/ui/Footer";
import "./globals.css";
import localFont from "next/font/local";
import { useRef, useState, useEffect } from "react";
import { Provider } from "react-redux";
import appStore from "@/store/store";
import Get_data from "./GetData";

const centuryGothic = localFont({
  src: "../../public/assets/fonts/CenturyGothic.ttf",
  variable: "--font-gothic",
});
const bigilla = localFont({
  src: "../../public/assets/fonts/Bigilla.otf",
  variable: "--font-bigilla",
});

// export const metadata = {
//   title: "Gulz",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const headerRef = useRef();
  const [isScrolled, setIsScrolled] = useState(false);

  const handleScroll = () => {
    setIsScrolled(window.scrollY > 100);
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <html lang="en">
      <body
        className={`${centuryGothic.variable} ${bigilla.variable} antialiased`}
      >
        <Provider store={appStore}>
          <Get_data>
            <HeaderNav headerRef={headerRef}
              isScrolled={isScrolled} />
            {children}
            <Footer />
          </Get_data>
        </Provider>
      </body>
    </html>
  );
}